### ISSUE TITLE
Interdire ternaire multi lignes 

### ISSUE THREAD

**Issue by alborq** [Geolid/phpcs#16]

**Comment by ektarum** [comment]
ton soucis c'était réellement un ternaire multi ligne ou un multi ternaire multi ligne ?

parce que ça présente quand meme mieux un ternaire sur plusieurs ligne parfois.

**Comment by devster** [comment]
Je suis assez d'accord avec @ektarum 
tu as des exemples à nous montrer @alborq ?

**Comment by alborq** [comment]
(Extrait de la PR source de l'issue)
```php
// [...] Some indent level
                $previousPeriodItems[$elementType] = isset($previousPeriodItems[$elementType]) ?
                    $previousPeriodItems[$elementType]: [];
                $periodItems[$elementType] = !isset($periodItems[$elementType]) ? $previousPeriodItems[$elementType]:
                    array_merge($previousPeriodItems[$elementType], $periodItems[$elementType]);
```
Le code ci-dessus passe le CS, je le trouve perso ilisible. 

Des ternaire sur deux ligne. 3 je dit pas.

**Comment by ektarum** [comment]
perso le multiligne je le verrais plus comme ça : 

```
$previousPeriodItems[$elementType] = isset($previousPeriodItems[$elementType]) 
  ? $previousPeriodItems[$elementType]
  : []
;
```

après les ternaires tu peux aussi faire un truc dégueux sur une ligne hein, mais ça veux pas dire qu'ils le sont tous ^^'

le premier pourrais ne pas etre un ternaire en passant :)

**Comment by alborq** [comment]
ça me va, on met du CS la dessus ?

**Comment by devster** [comment]
Si on peut avoir du CS pour la version d'alex ca serait top en effet
